const state={cases:[],current:null,timeline:[],approval:null};
const $=selector=>document.querySelector(selector);
const statusNames={draft:'草稿',testing:'试验中',remediation:'整改中',pending_review:'待技术审查',approved:'已批准'};
const stageNames={initial:'初期',stable:'稳定期',final:'终期'};
const metricNames={color_difference:'颜色差',water_absorption:'吸水率',adhesion_strength:'附着强度',surface_defect:'表面缺陷'};
const actionNames={record_observation:'录入下一阶段',record_final_evaluation:'补录终期评价',remediate_deviation:'处理偏差/复验',create_formula:'新增配方',register_patch:'登记试验块'};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=()=>crypto.randomUUID();
const fmt=value=>new Date(value).toLocaleString('zh-CN',{hour12:false});
const signed=value=>`${value>0?'+':''}${Number(value).toFixed(3)}`;

async function api(path,options={}){
  const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});
  const body=await response.json().catch(()=>({}));
  if(!response.ok){const error=new Error(body.error?.message||`请求失败 (${response.status})`);error.details=body.error||{};throw error}
  return body.data;
}
async function loadCases(selectID){state.cases=await api('/api/v1/restoration-cases');renderCaseList();if(selectID)await selectCase(selectID);else if(state.current)await selectCase(state.current.caseID)}
function renderCaseList(){const root=$('#caseList');if(!state.cases.length){root.innerHTML='<p class="muted">还没有试配任务。</p>';return}root.innerHTML=state.cases.map(c=>`<button class="case-item ${state.current?.caseID===c.caseID?'active':''}" data-case="${c.caseID}"><strong>${esc(c.siteName)}</strong><span>${esc(c.buildingArea)} · ${esc(c.stoneType)}</span><span>${statusNames[c.status]} · v${c.version}</span></button>`).join('');root.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>selectCase(b.dataset.case))}
async function selectCase(id){state.current=await api(`/api/v1/restoration-cases/${id}`);state.timeline=await api(`/api/v1/restoration-cases/${id}/timeline`);state.approval=null;if(state.current.approval){try{state.approval=await api(`/api/v1/restoration-cases/${id}/approval`)}catch(error){state.approval={...state.current.approval,verificationStatus:error.details?.verificationStatus||'snapshot_unparseable',integrityError:error.message}}}renderCaseList();renderCase()}
function renderCase(){$('#emptyState').classList.add('hidden');$('#caseView').classList.remove('hidden');$('#caseStatus').textContent=statusNames[state.current.status];$('#caseTitle').textContent=state.current.siteName;$('#caseSubtitle').textContent=`${state.current.buildingArea} · ${state.current.stoneType}`;$('#caseVersion').textContent=state.current.version;renderOverview();renderFormulas();renderDeviations();renderTimeline();renderApproval()}

function renderOverview(){
  const c=state.current,t=c.acceptanceThresholds,r=c.readiness;let actions='';
  if(c.status==='draft')actions+='<button data-action="baseline">修订验收基线</button><button data-action="formula" class="primary">新增配方</button>';
  if(['draft','testing','remediation'].includes(c.status)&&c.formulas.length)actions+='<button data-action="patch">登记试验块</button>';
  if(['testing','remediation'].includes(c.status))actions+=`<button data-action="submit" ${r.canSubmitReview?'':'disabled'}>提交技术审查</button>`;
  if(c.status==='pending_review')actions+='<button data-action="review" class="primary">技术审查决定</button>';
  const issues=r.issues.map(i=>`<li><div><strong>${esc(i.patchCode||'任务')}</strong> · ${esc(i.message)}${i.stage?`（下一步：${stageNames[i.stage]}）`:''}${i.metric?` · ${esc(metricNames[i.metric]||i.metric)}`:''}</div>${actionNames[i.suggestedAction]?`<button class="small" data-issue-action="${i.suggestedAction}" data-patch="${esc(i.patchID)}" data-stage="${esc(i.stage)}" data-deviation="${esc(i.deviationID)}">${actionNames[i.suggestedAction]}</button>`:''}</li>`).join('');
  $('#overview').innerHTML=`<div class="actions">${actions}</div><div class="grid"><article class="card"><span class="label">颜色差 ΔE 上限</span><div class="metric">≤ ${t.maxColorDifference}</div></article><article class="card"><span class="label">吸水率上限</span><div class="metric">≤ ${t.maxWaterAbsorption}%</div></article><article class="card"><span class="label">附着强度下限</span><div class="metric">≥ ${t.minAdhesionStrength} MPa</div></article><article class="card wide"><h3>修复目标</h3><p><span class="label">病害描述</span><br>${esc(c.deteriorationSummary)}</p><p><span class="label">目标外观</span><br>${esc(c.targetAppearance)}</p></article><article class="card wide"><div class="card-head"><h3>送审就绪度</h3><strong class="${r.canSubmitReview?'success':'danger'}">${r.canSubmitReview?'可以送审':'尚有阻断'}</strong></div><div class="summary-metrics"><span>已完成试验块 <strong>${r.completedPatchCount}/${r.totalPatchCount}</strong></span><span>开放偏差 <strong>${r.openDeviationCount}</strong></span></div>${issues?`<ul class="readiness-list">${issues}</ul>`:'<p class="success">全部终期证据与复验闭环已完成。</p>'}</article></div>`;
  bindActions($('#overview'));$('#overview').querySelectorAll('[data-issue-action]').forEach(button=>button.onclick=()=>openSuggestedAction(button));
}
function openSuggestedAction(button){const action=button.dataset.issueAction;if(action==='record_observation'||action==='record_final_evaluation')return observationDialog(button.dataset.patch,button.dataset.stage||'final');if(action==='create_formula')return formulaDialog();if(action==='register_patch')return patchDialog();const deviation=button.dataset.deviation||state.current.deviations.find(d=>d.patchID===button.dataset.patch&&d.status==='open')?.deviationID;if(deviation)return remediationDialog(deviation);toast('请先完成当前复验阶段，再处理该分支',true)}

function renderFormulas(){
  const c=state.current;
  const formulas=c.formulas.map(f=>`<article class="card"><div class="card-head"><h3>配方 R${f.revisionNumber}</h3><span class="label">${fmt(f.createdAt)}</span></div><div class="chips">${f.ingredients.map(i=>`<span class="chip">${esc(i.name)} ${i.percentage}%</span>`).join('')}</div><p><span class="label">施工工法</span><br>${esc(f.applicationMethod)}</p><p><span class="label">基材条件</span><br>${esc(f.substrateConditions)}</p><small>${esc(f.changeReason||'初始配方')} · ${esc(f.createdBy)}</small></article>`).join('');
  const ordered=[...c.patches].sort((a,b)=>a.rootPatchID.localeCompare(b.rootPatchID)||a.retestRound-b.retestRound||a.patchCode.localeCompare(b.patchCode));
  const patches=ordered.map(p=>{const next=['initial','stable','final'][p.observations.length];const rows=(p.trends||[]).map(trend=>`<tr><th>${stageNames[trend.stage]}</th>${trend.metrics.map(m=>`<td class="${m.worsening?'risk-cell':''}">${signed(m.change)}<small>余量 ${signed(m.thresholdMargin)}</small>${m.worsening?`<b>趋势预警${m.consecutiveWorsening?' · 连续恶化':''}</b>`:''}</td>`).join('')}</tr>`).join('');return `<article class="card trace round-${Math.min(p.retestRound,8)}"><div class="card-head"><h3>${esc(p.patchCode)}</h3><span class="${p.evaluationResult?.conclusion==='passed'?'success':p.evaluationResult?'danger':''}">${p.evaluationResult?.conclusion==='passed'?'合格':p.evaluationResult?'不合格':stageNames[p.curingStage]||'待观测'}</span></div><p class="label">根试验块 ${esc(p.rootPatchID)} · 第 ${p.retestRound} 轮${p.parentPatchID?` · 父块 ${esc(p.parentPatchID)}`:''}</p><div class="chips">${p.observations.map(o=>`<span class="chip">${stageNames[o.stage]} ΔE ${o.colorDifference} / 吸水 ${o.waterAbsorption}% / 附着 ${o.adhesionStrength}</span>`).join('')}</div>${rows?`<div class="table-wrap"><table class="trend-table"><thead><tr><th>阶段</th><th>颜色差变化</th><th>吸水率变化</th><th>附着强度变化</th></tr></thead><tbody>${rows}</tbody></table><p class="label">趋势预警用于提前复核；正式偏差仍只由终期评价生成。</p></div>`:''}${next&&['testing','remediation'].includes(c.status)?`<div class="actions"><button data-observe="${p.patchID}" data-stage="${next}" class="primary">录入${stageNames[next]}观测</button></div>`:''}</article>`}).join('');
  $('#formulas').innerHTML=`<div class="actions">${c.status==='draft'?'<button data-action="formula" class="primary">新增配方</button>':''}${c.formulas.length&&['draft','testing','remediation'].includes(c.status)?'<button data-action="patch">登记试验块</button>':''}</div><h3>配方修订</h3><div class="grid">${formulas||'<p class="muted">尚无配方。</p>'}</div><h3>试验块与复验链</h3><div class="stack">${patches||'<p class="muted">尚无试验块。</p>'}</div>`;
  bindActions($('#formulas'));$('#formulas').querySelectorAll('[data-observe]').forEach(b=>b.onclick=()=>observationDialog(b.dataset.observe,b.dataset.stage));
}
function renderDeviations(){const c=state.current;$('#deviations').innerHTML=`<div class="stack">${c.deviations.map(d=>{const p=c.patches.find(p=>p.patchID===d.patchID);return `<article class="card"><div class="card-head"><h3>${esc(metricNames[d.metric]||d.metric)} · ${esc(p?.patchCode||d.patchID)}</h3><span class="status">${d.status}</span></div><p>实测 <strong>${esc(d.measuredValue)}</strong>；阈值 <strong>${esc(d.threshold)}</strong>；等级 ${esc(d.severity)}</p>${d.cause?`<p><span class="label">原因与处置</span><br>${esc(d.cause)} — ${esc(d.disposition)}</p>`:''}${d.status==='open'?`<button data-remediate="${d.deviationID}" class="primary">登记整改与下一轮复验</button>`:''}${d.retestPatchID?`<p class="label">直接复验块 ${esc(d.retestPatchID)}</p>`:''}</article>`}).join('')||'<p class="muted">当前没有偏差。</p>'}</div>`;$('#deviations').querySelectorAll('[data-remediate]').forEach(b=>b.onclick=()=>remediationDialog(b.dataset.remediate))}
function renderTimeline(){$('#timeline').innerHTML=state.timeline.map(e=>`<div class="timeline-item" data-event-id="${e.eventID}" data-event-type="${e.eventType}"><strong>${esc(e.summary)}</strong><p class="muted">${esc(e.actor)} · ${esc(e.eventType)}</p><time>${fmt(e.occurredAt)}</time></div>`).join('')||'<p class="muted">暂无事件。</p>'}
function renderApproval(){const a=state.approval;if(!a){$('#approval').innerHTML='<p class="muted">任务批准后将在此生成不可变批准记录。</p>';return}if(a.verificationStatus!=='verified'){$('#approval').innerHTML=`<article class="card integrity-failed"><h2>批准证据未通过核验</h2><p class="danger">${esc(a.integrityError||a.verificationStatus)}</p><p>批准编号 ${esc(a.approvalID)} · 冻结版本 v${a.frozenCaseVersion}</p><code>${esc(a.snapshotDigest)}</code><p class="muted">系统未把损坏或摘要不匹配的快照展示为有效证据，也未改写原记录。</p></article>`;return}const e=a.evidence,f=e.approvedFormula;const patches=e.patches.map(p=>`<article class="evidence-block"><div class="card-head"><strong>${esc(p.patchCode)} · 第 ${p.retestRound} 轮</strong><button class="small" data-locate="patch.evaluated" data-entity="${p.patchID}">定位时间线</button></div>${p.observations.map(o=>`<p>${stageNames[o.stage]}：ΔE ${o.colorDifference}，吸水 ${o.waterAbsorption}%，附着 ${o.adhesionStrength} MPa · ${esc(o.evidenceSummary)}</p>`).join('')}<span class="${p.evaluationResult?.conclusion==='passed'?'success':'danger'}">${p.evaluationResult?.conclusion==='passed'?'合格':'不合格'}</span></article>`).join('');const deviations=e.deviations.map(d=>`<li>${esc(metricNames[d.metric]||d.metric)} · ${esc(d.status)}${d.closedAt?` · 关闭于 ${fmt(d.closedAt)}`:''} <button class="small" data-locate="deviation.remediated" data-entity="${d.deviationID}">定位时间线</button></li>`).join('')||'<li>无偏差</li>';$('#approval').innerHTML=`<article class="card"><div class="approval-seal"><span>已核验 · 技术批准记录</span><h2>${esc(a.approvalID)}</h2><p>冻结任务版本 v${a.frozenCaseVersion}</p></div><div class="evidence-block"><h3>冻结验收阈值</h3><p>颜色差 ≤ ${e.thresholds.maxColorDifference}；吸水率 ≤ ${e.thresholds.maxWaterAbsorption}%；附着强度 ≥ ${e.thresholds.minAdhesionStrength} MPa</p></div><div class="evidence-block"><div class="card-head"><h3>获批配方 R${f.revisionNumber}</h3><button class="small" data-locate="formula.created" data-entity="${f.formulaID}">定位时间线</button></div><div class="chips">${f.ingredients.map(i=>`<span class="chip">${esc(i.name)} ${i.percentage}%</span>`).join('')}</div><p>${esc(f.applicationMethod)} · ${esc(f.substrateConditions)}</p></div><h3>冻结试验观测与评价</h3>${patches}<h3>偏差闭环</h3><ul>${deviations}</ul><p><span class="label">审查意见</span><br>${esc(a.reviewComment)}</p><p><span class="label">批准负责人 / 时间</span><br>${esc(a.decidedBy)} · ${fmt(a.decidedAt)}</p><p><span class="label">内容摘要 SHA-256</span><br><code>${esc(a.snapshotDigest)}</code></p></article>`;$('#approval').querySelectorAll('[data-locate]').forEach(b=>b.onclick=()=>focusTimeline(b.dataset.locate,b.dataset.entity))}
function focusTimeline(type,entityID){document.querySelector('[data-tab="timeline"]').click();const matchesEntity=item=>!entityID||Object.values(item.data||{}).some(value=>value===entityID||(Array.isArray(value)&&value.includes(entityID)));let event=state.timeline.find(item=>(!type||item.eventType===type)&&matchesEntity(item));if(!event&&entityID)event=state.timeline.find(matchesEntity);const node=event?$(`#timeline [data-event-id="${event.eventID}"]`):null;if(node){node.classList.add('focused');node.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>node.classList.remove('focused'),1800)}else toast('时间线中未找到对应事件',true)}

function bindActions(root){root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>({baseline:baselineDialog,formula:formulaDialog,patch:patchDialog,submit:submitReview,review:reviewDialog}[b.dataset.action]()))}
function field(name,label,type='text',value='',extra=''){return `<div class="field"><label for="f-${name}">${label}</label>${type==='textarea'?`<textarea id="f-${name}" name="${name}" ${extra}>${esc(value)}</textarea>`:`<input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}>`}</div>`}
function openDialog(title,html,onSubmit){$('#dialogTitle').textContent=title;$('#dialogFields').innerHTML=html;$('#formError').classList.add('hidden');$('#actionForm').onsubmit=async event=>{event.preventDefault();const submit=event.submitter;submit.disabled=true;try{await onSubmit(new FormData(event.target));$('#actionDialog').close();toast('操作已保存');await loadCases(state.current?.caseID)}catch(error){$('#formError').textContent=error.message;$('#formError').classList.remove('hidden')}finally{submit.disabled=false}};$('#actionDialog').showModal()}
function meta(){return {expectedVersion:state.current.version,idempotencyKey:key(),actor:'当前试验员'}}
function ingredients(data){return String(data.get('ingredients')).split('\n').filter(Boolean).map(line=>{const [name,percentage]=line.split(',');return {name:name.trim(),percentage:Number(percentage)}})}
function baselineDialog(){const c=state.current,t=c.acceptanceThresholds;openDialog('修订草稿验收基线',field('deteriorationSummary','病害描述','textarea',c.deteriorationSummary)+field('targetAppearance','目标外观','textarea',c.targetAppearance)+field('maxColorDifference','颜色差 ΔE 上限','number',t.maxColorDifference,'step="0.01"')+field('maxWaterAbsorption','吸水率上限 %','number',t.maxWaterAbsorption,'step="0.01"')+field('minAdhesionStrength','附着强度下限 MPa','number',t.minAdhesionStrength,'step="0.01"')+field('reason','修订原因','textarea'),async d=>api(`/api/v1/restoration-cases/${c.caseID}/baseline-revisions`,{method:'POST',body:JSON.stringify({...meta(),deteriorationSummary:d.get('deteriorationSummary'),targetAppearance:d.get('targetAppearance'),acceptanceThresholds:{maxColorDifference:Number(d.get('maxColorDifference')),maxWaterAbsorption:Number(d.get('maxWaterAbsorption')),minAdhesionStrength:Number(d.get('minAdhesionStrength'))},reason:d.get('reason')})}))}
function formulaDialog(){openDialog('新增配方修订',field('ingredients','原料与比例（每行：名称,比例）','textarea','石灰,60\n石英砂,40')+field('applicationMethod','施工工法','textarea')+field('substrateConditions','基材条件','textarea')+field('changeReason','修订原因','textarea','初始试配'),async d=>api(`/api/v1/restoration-cases/${state.current.caseID}/formulas`,{method:'POST',body:JSON.stringify({...meta(),ingredients:ingredients(d),applicationMethod:d.get('applicationMethod'),substrateConditions:d.get('substrateConditions'),changeReason:d.get('changeReason')})}))}
function patchDialog(){const options=state.current.formulas.map(f=>`<option value="${f.formulaID}">R${f.revisionNumber} · ${esc(f.changeReason)}</option>`).join('');openDialog('登记试验块',`<div class="field"><label>配方</label><select name="formulaID">${options}</select></div>`+field('patchCodes','试验块编号（单块一行；成组登记填写 2–50 行）','textarea'),async d=>{const codes=String(d.get('patchCodes')).split('\n').map(v=>v.trim()).filter(Boolean);const payload={...meta(),formulaID:d.get('formulaID')};if(codes.length===1)payload.patchCode=codes[0];else payload.patchCodes=codes;return api(`/api/v1/restoration-cases/${state.current.caseID}/patches`,{method:'POST',body:JSON.stringify(payload)})})}
function observationDialog(patchID,stage){const patch=state.current.patches.find(p=>p.patchID===patchID);const boundary=patch?.observations.at(-1)?.observedAt||patch?.createdAt;const suggested=new Date(Math.max(Date.now(),new Date(boundary).getTime()+1000)).toISOString().slice(0,19);openDialog(`录入${stageNames[stage]}观测`,field('colorDifference','颜色差 ΔE','number','1.5','step="0.001" min="0"')+field('waterAbsorption','吸水率 %','number','3','step="0.001" min="0"')+field('adhesionStrength','附着强度 MPa','number','1.2','step="0.001" min="0"')+field('surfaceDefects','表面缺陷（每行一项，可空）','textarea')+field('observedAt','观测时间','datetime-local',suggested,'step="1"')+field('evidenceSummary','证据摘要','textarea'),async d=>api(`/api/v1/restoration-cases/${state.current.caseID}/patches/${patchID}/observations`,{method:'POST',body:JSON.stringify({...meta(),stage,colorDifference:Number(d.get('colorDifference')),waterAbsorption:Number(d.get('waterAbsorption')),adhesionStrength:Number(d.get('adhesionStrength')),surfaceDefects:String(d.get('surfaceDefects')).split('\n').filter(Boolean),observedAt:new Date(d.get('observedAt')).toISOString(),evidenceSummary:d.get('evidenceSummary')})}))}
function remediationDialog(deviationID){openDialog('偏差整改与下一轮复验',field('cause','原因分析','textarea')+field('disposition','处置说明','textarea')+field('ingredients','替代配方（每行：名称,比例）','textarea','石灰,55\n石英砂,45')+field('applicationMethod','施工工法','textarea')+field('substrateConditions','基材条件','textarea')+field('changeReason','配方修订原因','textarea')+field('retestPatchCode','复验块编号'),async d=>api(`/api/v1/restoration-cases/${state.current.caseID}/deviations/${deviationID}/remediation`,{method:'POST',body:JSON.stringify({...meta(),cause:d.get('cause'),disposition:d.get('disposition'),ingredients:ingredients(d),applicationMethod:d.get('applicationMethod'),substrateConditions:d.get('substrateConditions'),changeReason:d.get('changeReason'),retestPatchCode:d.get('retestPatchCode')})}))}
async function submitReview(){if(!state.current.readiness.canSubmitReview)return toast('请先按阻断清单补齐证据',true);if(!confirm('确认所有终期证据与偏差闭环均已完成，并提交技术审查？'))return;try{await api(`/api/v1/restoration-cases/${state.current.caseID}/submit-review`,{method:'POST',body:JSON.stringify(meta())});toast('已提交技术审查');await loadCases(state.current.caseID)}catch(error){toast(error.message,true)}}
function reviewDialog(){const options=state.current.formulas.map(f=>`<option value="${f.formulaID}">R${f.revisionNumber}</option>`).join('');openDialog('技术审查决定',`<div class="field"><label>结论</label><select name="decision"><option value="approve">批准并冻结</option><option value="return">退回整改</option></select></div><div class="field"><label>获批配方</label><select name="approvedFormulaID">${options}</select></div>`+field('reviewComment','审查意见','textarea'),async d=>api(`/api/v1/restoration-cases/${state.current.caseID}/review-decisions`,{method:'POST',body:JSON.stringify({...meta(),decision:d.get('decision'),approvedFormulaID:d.get('approvedFormulaID'),reviewComment:d.get('reviewComment')})}))}
function newCaseDialog(){openDialog('创建修复试配任务',field('siteName','项目 / 建筑名称')+field('buildingArea','建筑部位')+field('stoneType','石材类型')+field('deteriorationSummary','病害描述','textarea')+field('targetAppearance','目标外观','textarea')+field('maxColorDifference','颜色差 ΔE 上限','number','3','step="0.01"')+field('maxWaterAbsorption','吸水率上限 %','number','5','step="0.01"')+field('minAdhesionStrength','附着强度下限 MPa','number','1','step="0.01"'),async d=>{const value=await api('/api/v1/restoration-cases',{method:'POST',body:JSON.stringify({idempotencyKey:key(),actor:'当前试验员',siteName:d.get('siteName'),buildingArea:d.get('buildingArea'),stoneType:d.get('stoneType'),deteriorationSummary:d.get('deteriorationSummary'),targetAppearance:d.get('targetAppearance'),acceptanceThresholds:{maxColorDifference:Number(d.get('maxColorDifference')),maxWaterAbsorption:Number(d.get('maxWaterAbsorption')),minAdhesionStrength:Number(d.get('minAdhesionStrength'))}})});state.current=value})}
function toast(message,bad=false){const node=$('#toast');node.textContent=message;node.classList.toggle('bad',bad);node.classList.remove('hidden');setTimeout(()=>node.classList.add('hidden'),3500)}
document.querySelectorAll('.tabs button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.add('hidden'));button.classList.add('active');$('#'+button.dataset.tab).classList.remove('hidden')});
$('#newCaseButton').onclick=newCaseDialog;$('#refreshButton').onclick=()=>loadCases(state.current?.caseID);$('#closeDialog').onclick=()=>$('#actionDialog').close();$('#cancelDialog').onclick=()=>$('#actionDialog').close();loadCases().catch(error=>toast(error.message,true));
